apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kara
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jagadeeshm2910/kube
    targetRevision: main
    path: kara
  destination:
    server: https://kubernetes.default.svc
    namespace: kara
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
